name: Build Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Nodejs Version To 12.x
        uses: actions/setup-node@v1.1.0
        with:
          node-version: '12.x'

      - name: Install Dependencies
        run: npm install

      - name: Unit Tests
        run: npm test

      - name: Build Source
        run: npm run build
